---
#### Ansible Playbook to perform Kernel Patching on RHEL/CentOS and Ubuntu/Debian Servers ####

- hosts: all
  serial: 4

  tasks:
    - name: install Apache on Solaris
      pkg5: name=web/server/apache-24
      when: ansible_os_family == "Solaris"
 
    - name: install Apache on RHEL
      yum:  name=httpd
      when: ansible_os_family == "RedHat"
 
    - name: start Apache
      service: name={{ apache }} state=started
