---
#### Ansible Playbook to perform Kernel Patching on RHEL/CentOS and Ubuntu/Debian Servers ####

- hosts: all
  serial: 4

  tasks:

   - name: update the system
    yum:
      name: "*"
      state: latest
