---
#### Ansible Playbook to perform Kernel Patching on RHEL/CentOS and Ubuntu/Debian Servers ####

- hosts: all
  serial: 4

  tasks:   
   - name: Remove  Apache on Solaris
     pkg5:
      name: name=web/server/apache-24
      state: absent
